<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>EtherCAT.App</RootNamespace>
    <ApplicationIcon />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.22" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.22" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.22" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EtherCAT.Core\EtherCAT.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\esi\**\*.xml" LinkBase="esi" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
